### ISSUE TITLE
XEPs and RFCs support page with version

### ISSUE THREAD

**Issue by Neustradamus** [telldus/xmppjs-client-plugins#3]
It is possible to have a XEPs and RFCs support page with version (XEP-XXXX v1.2)?

Examples:
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/gajimxepsupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by rimzici** [comment]
Added. OMEMO is slightly outdated.

**Comment by Neustradamus** [comment]
@rimzici: Thanks!

OMEMO 0.3.0 is nice if there is 12 byte IV.
Do you confirm?

**Comment by rimzici** [comment]
Yes. Check [EncryptionPayloadType](https://github.com/telldus/xmppjs-client-plugins/blob/master/packages/xep-0384-omemo/index.js#L114).

**Comment by Neustradamus** [comment]
@rimzici: Thanks :)
